name: Check Naming Conventions

on:
  pull_request:
    types:
      - labeled

jobs:
  naming-conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # or your preferred version

      - name: Check for Specific Label
        id: check-label
        run: |
          echo "Label received: ${{ github.event.label.name }}"
          if [[ "${{ github.event.label.name }}" == "api-testcase" || "${{ github.event.label.name }}" == "ui-testcase" ]]; then
            echo "Label matches"
            echo "match=true" >> $GITHUB_ENV
          else
            echo "Label does not match"
            echo "match=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: npm install

      - name: List files in unitTest directory
        run: ls -al unitTest/

      - name: Compile TypeScript
        run: npx tsc unitTest/unitTest.ts

      - name: Run naming convention checks
        run: node ./unitTest/unitTest.js
